version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Opcional: montar código para desarrollo
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    container_name: procesamiento-imagenes-web
    
    # Limitar recursos del contenedor
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M