#!/bin/bash
# Script de ejemplo para ejecutar el pipeline completo
# Este archivo muestra diferentes formas de usar pipeline_entrenamiento.py

echo "════════════════════════════════════════════════════════════════"
echo "🎯 EJEMPLOS DE USO - Pipeline de Entrenamiento"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Colores para output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}1. Entrenamiento Rápido (Testing)${NC}"
echo "   Ideal para verificar que todo funciona"
echo "   Duración: ~10 minutos"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --epochs 5 \\"
echo "  --batch-size 4 \\"
echo "  --num-augmentations 1 \\"
echo "  --test-split 0.2 \\"
echo "  --output-dir results_test"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}2. Entrenamiento Estándar (Recomendado)${NC}"
echo "   Configuración balanceada para buenos resultados"
echo "   Duración: ~2-4 horas"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --epochs 100 \\"
echo "  --batch-size 8 \\"
echo "  --num-augmentations 2 \\"
echo "  --save-every 15 \\"
echo "  --patience 5 \\"
echo "  --enhance \\"
echo "  --amp \\"
echo "  --output-dir results_standard"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}3. Entrenamiento Largo (Máxima Precisión)${NC}"
echo "   Para obtener el mejor modelo posible"
echo "   Duración: ~10-20 horas"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --epochs 1000 \\"
echo "  --batch-size 8 \\"
echo "  --num-augmentations 3 \\"
echo "  --save-every 20 \\"
echo "  --patience 10 \\"
echo "  --enhance \\"
echo "  --amp \\"
echo "  --output-dir results_full"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}4. Reanudar Entrenamiento Interrumpido${NC}"
echo "   Si el entrenamiento se detuvo (corte de luz, etc.)"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --skip-stages split augment \\"
echo "  --resume results_full/checkpoint_epoch_45.pth \\"
echo "  --epochs 1000 \\"
echo "  --batch-size 8 \\"
echo "  --enhance \\"
echo "  --amp \\"
echo "  --output-dir results_full"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}5. Solo Evaluación (Modelo Ya Entrenado)${NC}"
echo "   Si ya tienes un modelo y solo quieres testearlo"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --skip-stages split augment train \\"
echo "  --output-dir results_full \\"
echo "  --test-output test_results_new"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}6. Experimento con Hiperparámetros${NC}"
echo "   Para probar diferentes configuraciones"
echo ""
echo "python3 pipeline_entrenamiento.py \\"
echo "  --epochs 50 \\"
echo "  --batch-size 16 \\"
echo "  --learning-rate 5e-5 \\"
echo "  --num-augmentations 1 \\"
echo "  --test-split 0.15 \\"
echo "  --output-dir results_exp1"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${GREEN}📊 Ver Resultados Después del Entrenamiento:${NC}"
echo ""
echo "# Ver resumen del pipeline"
echo "cat results_full/pipeline_results.json"
echo ""
echo "# Ver métricas de test"
echo "cat test_results/test_metrics.json"
echo ""
echo "# Ver historial de entrenamiento (últimas 5 épocas)"
echo "cat results_full/training_log.json | jq '.[-5:]'"
echo ""
echo "# Ver imágenes con detecciones"
echo "ls test_results/*_detected.jpg"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""

# ─────────────────────────────────────────────────────────────────
echo -e "${GREEN}🔍 Verificar Estado Antes de Empezar:${NC}"
echo ""
echo "# Contar imágenes y XMLs"
echo "echo \"Imágenes: \$(ls dataset/images/ | wc -l)\""
echo "echo \"XMLs: \$(ls dataset/xmls/ | wc -l)\""
echo ""
echo "# Verificar GPU disponible"
echo "python3 -c 'import torch; print(f\"GPU: {torch.cuda.is_available()}\")'"
echo ""
echo "# Verificar espacio en disco"
echo "df -h . | grep -v Filesystem"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo -e "${GREEN}✅ Para ejecutar cualquier ejemplo, copia el comando y pégalo en la terminal${NC}"
echo ""
